In [6]:
import pandas as pd

X = pd.read_csv('data/raw/features.csv')
y = pd.read_csv('data/raw/targets.csv')

In [7]:
X.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba

In [8]:
X["native-country"].unique()

<StringArray>
[             'United-States',                       'Cuba',
                    'Jamaica',                      'India',
                          '?',                     'Mexico',
                      'South',                'Puerto-Rico',
                   'Honduras',                    'England',
                     'Canada',                    'Germany',
                       'Iran',                'Philippines',
                      'Italy',                     'Poland',
                   'Columbia',                   'Cambodia',
                   'Thailand',                    'Ecuador',
                       'Laos',                     'Taiwan',
                      'Haiti',                   'Portugal',
         'Dominican-Republic',                'El-Salvador',
                     'France',                  'Guatemala',
                      'China',                      'Japan',
                 'Yugoslavia',                       'Peru',
 'Outlying-US(Guam-USVI-etc)',                   'Scotland',
            'Trinadad&Tobago',                     'Greece',
                  'Nicaragua',                    'Vietnam',
                       'Hong',                    'Ireland',
                    'Hungary',         'Holand-Netherlands',
                          nan]
Length: 43, dtype: str

In [9]:
X = X[X['workclass'].notna()]

In [10]:
X = X.dropna(subset=['occupation'])
X.occupation.isna().sum()

np.int64(0)

In [11]:
X = X[X['occupation'] != '?']

In [12]:
X.shape

(46033, 14)

In [13]:
X.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country'],
      dtype='str')

In [14]:
y.value_counts()

income
<=50K     24720
<=50K.    12435
>50K       7841
>50K.      3846
Name: count, dtype: int64

In [15]:
X.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,46033.000000,4.603300e+04,46033.000000,46033.000000,46033.000000,46033.000000
mean,38.556601,1.898051e+05,10.128929,1114.332653,88.729346,40.948407
std,13.204268,1.054747e+05,2.564064,7589.571484,405.316932,12.011069
min,17.000000,1.349200e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.176060e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783530e+05,10.000000,0.000000,0.000000,40.000000
75%,47.000000,2.378650e+05,13.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [16]:
X.info()

<class 'pandas.DataFrame'>
Index: 46033 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             46033 non-null  int64
 1   workclass       46033 non-null  str
 2   fnlwgt          46033 non-null  int64
 3   education       46033 non-null  str
 4   education-num   46033 non-null  int64
 5   marital-status  46033 non-null  str
 6   occupation      46033 non-null  str
 7   relationship    46033 non-null  str
 8   race            46033 non-null  str
 9   sex             46033 non-null  str
 10  capital-gain    46033 non-null  int64
 11  capital-loss    46033 non-null  int64
 12  hours-per-week  46033 non-null  int64
 13  native-country  45778 non-null  str
dtypes: int64(6), str(8)
memory usage: 5.3 MB

In [17]:
X.shape

(46033, 14)

In [18]:
X[X.occupation.isna()]

Empty DataFrame
Columns: [age, workclass, fnlwgt, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loss, hours-per-week, native-country]
Index: []

In [19]:
y.shape

(48842, 1)

In [20]:
y['income'] = y['income'].str.strip().str.replace('.','', regex=False)

In [21]:
y.value_counts()

income
<=50K     37155
>50K      11687
Name: count, dtype: int64

In [23]:
import os

path = 'data/processed'

os.makedirs(path, exist_ok=True)

y.to_csv(os.path.join(path, 'proccessed_features.csv'))
X.to_csv(os.path.join(path, 'proccessed_targets.csv'))